/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MapRouteImport } from './routes/map'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpportunitiesIdRouteImport } from './routes/opportunities.$id'
import { Route as DiscoveryRunIdRouteImport } from './routes/discovery.$runId'
import { Route as ApiOpportunityMapRouteImport } from './routes/api/opportunity-map'

const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIdRoute = OpportunitiesIdRouteImport.update({
  id: '/opportunities/$id',
  path: '/opportunities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryRunIdRoute = DiscoveryRunIdRouteImport.update({
  id: '/discovery/$runId',
  path: '/discovery/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpportunityMapRoute = ApiOpportunityMapRouteImport.update({
  id: '/api/opportunity-map',
  path: '/api/opportunity-map',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/map': typeof MapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRoute
  '/api/opportunity-map': typeof ApiOpportunityMapRoute
  '/discovery/$runId': typeof DiscoveryRunIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/map': typeof MapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRoute
  '/api/opportunity-map': typeof ApiOpportunityMapRoute
  '/discovery/$runId': typeof DiscoveryRunIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/map': typeof MapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRoute
  '/api/opportunity-map': typeof ApiOpportunityMapRoute
  '/discovery/$runId': typeof DiscoveryRunIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/map'
    | '/sitemap.xml'
    | '/sources'
    | '/api/opportunity-map'
    | '/discovery/$runId'
    | '/opportunities/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/map'
    | '/sitemap.xml'
    | '/sources'
    | '/api/opportunity-map'
    | '/discovery/$runId'
    | '/opportunities/$id'
  id:
    | '__root__'
    | '/'
    | '/discover'
    | '/map'
    | '/sitemap.xml'
    | '/sources'
    | '/api/opportunity-map'
    | '/discovery/$runId'
    | '/opportunities/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverRoute: typeof DiscoverRoute
  MapRoute: typeof MapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SourcesRoute: typeof SourcesRoute
  ApiOpportunityMapRoute: typeof ApiOpportunityMapRoute
  DiscoveryRunIdRoute: typeof DiscoveryRunIdRoute
  OpportunitiesIdRoute: typeof OpportunitiesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$id': {
      id: '/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof OpportunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery/$runId': {
      id: '/discovery/$runId'
      path: '/discovery/$runId'
      fullPath: '/discovery/$runId'
      preLoaderRoute: typeof DiscoveryRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/opportunity-map': {
      id: '/api/opportunity-map'
      path: '/api/opportunity-map'
      fullPath: '/api/opportunity-map'
      preLoaderRoute: typeof ApiOpportunityMapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverRoute: DiscoverRoute,
  MapRoute: MapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SourcesRoute: SourcesRoute,
  ApiOpportunityMapRoute: ApiOpportunityMapRoute,
  DiscoveryRunIdRoute: DiscoveryRunIdRoute,
  OpportunitiesIdRoute: OpportunitiesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
